### ISSUE TITLE
[Bug/Crash] Game fail to load correctly on version 1.3.11 of lexiconfig

### ISSUE THREAD

**Issue by AlexFromPoland** [CodinGlitch/SimpleRadio#42] opened 2024-06-20 14:31 UTC
**Describe the bug**
Game have problem to load correctly simple Radio mod (version 2.3.4 and above)
on version 1.3.11 of lexiconfig 

**To Reproduce**
1. Go to curseforge app and download simple Radio mod , (by default courseforge install newest version of lexiconfig)
3. launch game

**Expected behavior**
i expect to launch game correctly

**Screenshots**
![Zrzut ekranu 2024-06-20 162343](https://github.com/CodinGlitch/SimpleRadio/assets/102538189/41589dd2-356b-458f-b23e-dfeccc209f2f)
**Version and Mod Loader:**
- Minecraft Version: 1.20.1
- Simple Radio Version: [2.3.4  2.3.5  2.3.6]
- Mod Loader: Forge

**Additional context**
Game have no problem to load on version 1.2.11 of lexiconfig

**Comment by CodinGlitch** [comment] 2024-06-20 22:25
duplicate of #39

**Closed as completed by CodinGlitch** 2024-06-20 22:25 UTC
Labels: bug
