### ISSUE TITLE
[Request] Compatibility for Mod EMI/JEI

### ISSUE THREAD

**Issue by YeraX7** [CodinGlitch/SimpleRadio#54] opened 2024-07-22 01:20 UTC
**Mod**
EMI/JEI Crafting recepies mods.

**Describe the compatibility you'd like**
I don't know if it's a bug or incompatibility, but it seems there is no way to craft or view crafting through the EMI mod. I would like it to be viewable through this mod to know how to craft everything.

**Comment by CodinGlitch** [comment] 2024-07-24 04:11
duplicate of #33, recipe browsers should work, but are being suppressed with the presence of FFAPI or any similar mods; the datapack provided there should be used as a temporary patch until it is resolved

**Closed as completed by CodinGlitch** 2024-07-24 04:11 UTC
Labels: compatibility
